# Generated by Django 6.0.6 on 2026-06-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_ca', models.CharField(max_length=100, null=True)),
                ('name_es', models.CharField(max_length=100, null=True)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(upload_to='projects/')),
                ('description', models.TextField()),
                ('description_ca', models.TextField(null=True)),
                ('description_es', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('tech_stack', models.CharField(max_length=200)),
                ('github_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Database', 'Database'), ('DevOps', 'DevOps'), ('Other', 'Other')], max_length=20)),
                ('icon', models.ImageField(upload_to='developer_portfolio/static/developer_portfolio/image/icons/')),
            ],
        ),
    ]
