# Generated by Django 6.0.6 on 2026-06-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor'), ('Field Archery', 'Field Archery'), ('3D Archery', '3D Archery')], max_length=100)),
                ('date', models.DateField()),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('mark', models.CharField(blank=True, max_length=100, null=True)),
                ('competition_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
